all: main.o registre.o
	gcc -o registre main.o registre.o
	
main.o: main.c
	gcc -c main.c -Wall -ansi -pedantic -o main.o
	
registre.o: registre.c
	gcc -c registre.c -Wall -ansi -pedantic -o registre.o
